pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/JunkYak/devopsProject', branch: 'main'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'pip install -r requirements.txt'
            }
        }

        stage('Run Collector') {
            steps {
                bat 'python src/main/collector.py'
            }
        }

        stage('Run Metrics') {
            steps {
                bat 'python src/main/metrics.py'
            }
        }
    }
}