pipeline {
    agent any

    triggers {
        githubPush()
    }

    environment {
        PYTHON = '"C:\\Users\\Priya Agrawal\\AppData\\Local\\Programs\\Python\\Python313\\python.exe"'
    }

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/priyaaaa70/devopsProject', branch: 'main'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat "%PYTHON% -m pip install -r requirements.txt"
            }
        }

        stage('Run Collector') {
            steps {
                bat "%PYTHON% src/main/collector.py"
            }
        }

        stage('Run Metrics') {
            steps {
                bat "%PYTHON% src/main/metrics.py"
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}